version: '3.3'
services:
  backend:
    container_name: teletherap-backend
    image: teletherap/backend:${IMAGE_VERSION}
    build: ./backend/
    depends_on:
      - database
    environment:
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - NUM_WORKERS=$BACKEND_NUM_WORKERS
      - MYSQL_DATABASE
      - SECRET_KEY
      - ADMIN_USERNAME
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - BASE_URL
      - VERIFICATION_PATH
      - GMAIL_ADDRESS
      - GMAIL_PASSWORD
      - PAYMENT_BASE_URL
      - PAYMENT_MERCHANT
    volumes:
      - django_static:/mnt/django-static/
      - ./.media:/mnt/media/

  frontend:
    image: teletherap/frontend:$IMAGE_VERSION
    container_name: teletherap-frontend
    build: ./frontend/
    depends_on:
      - backend
    volumes:
      - frontend:/mnt/frontend/

  database:
    image: mysql:latest
    container_name: teletherap-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./.db-data:/var/lib/mysql
    tty: true

  nginx:
    image: nginx:1.19.4-alpine
    container_name: teletherap-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend:/mnt/frontend/:ro
      - django_static:/mnt/django-static/:ro
      - ./.media:/mnt/media/:ro
    restart: always

volumes:
  frontend:
  django_static:
