# Generated by Django 4.1 on 2022-08-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_accountactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='daily_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='daily_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='expertise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='license_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='price_per_session',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
