# Generated by Django 4.1 on 2022-08-21 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_therapist_daily_end_time_therapist_daily_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_username',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9_]{5,})$', 'Telegram username must be alphanumeric and at least 5 characters long.')]),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='telegram_username',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9_]{5,})$', 'Telegram username must be alphanumeric and at least 5 characters long.')]),
        ),
    ]
