# Generated by Django 4.1 on 2022-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_withdrawal_destination_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtransaction',
            name='is_rollbacked',
            field=models.BooleanField(default=False),
        ),
    ]
