# Generated by Django 4.1 on 2022-08-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_therapist_daily_end_time_therapist_daily_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('communication_type', models.CharField(choices=[('tlgrm', 'Telegram'), ('gmeet', 'Google Meet')], default='tlgrm', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='user.client')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='user.therapist')),
            ],
        ),
    ]
