# Generated by Django 4.1 on 2022-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('resd', 'Reserved'), ('attd', 'Attended'), ('cnl', 'Cancelled')], default='resd', max_length=4),
        ),
    ]
