# Generated by Django 4.1 on 2022-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_reservation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='communication_type',
            field=models.CharField(choices=[('tlgrm', 'Telegram'), ('video', 'Video')], default='tlgrm', max_length=5),
        ),
    ]
