# Generated by Django 4.1 on 2022-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_alter_reservation_communication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='url_for_client',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='url_for_therapist',
            field=models.URLField(null=True),
        ),
    ]
