# Generated by Django 4.1 on 2022-08-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_reservation_url_for_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('resd', 'Reserved'), ('ongo', 'Ongoing'), ('attd', 'Attended'), ('cnl', 'Cancelled')], default='resd', max_length=4),
        ),
    ]
