# Generated by Django 4.1 on 2022-08-22 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0006_alter_reservation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='url_for_client',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='url_for_therapist',
        ),
        migrations.AddField(
            model_name='reservation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
