// account:
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ACTIVATION_REQUEST = 'ACTIVATION_REQUEST';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const GET_PERSONAL_THERAPIST_INFO_REQUEST = 'GET_PERSONAL_THERAPIST_INFO_REQUEST';
export const GET_PERSONAL_THERAPIST_INFO_SUCCESS = 'GET_PERSONAL_THERAPIST_INFO_SUCCESS';
export const GET_PERSONAL_THERAPIST_INFO_FAILURE = 'GET_PERSONAL_THERAPIST_INFO_FAILURE';

export const UPDATE_PERSONAL_THERAPIST_INFO_REQUEST = 'UPDATE_PERSONAL_THERAPIST_INFO_REQUEST';
export const UPDATE_PERSONAL_THERAPIST_INFO_SUCCESS = 'UPDATE_PERSONAL_THERAPIST_INFO_SUCCESS';
export const UPDATE_PERSONAL_THERAPIST_INFO_FAILURE = 'UPDATE_PERSONAL_THERAPIST_INFO_FAILURE';

export const REMOVE_THERAPIST_DOCUMENT_REQUEST = 'REMOVE_THERAPIST_DOCUMENT_REQUEST';
export const REMOVE_THERAPIST_DOCUMENT_SUCCESS = 'REMOVE_THERAPIST_DOCUMENT_SUCCESS';
export const REMOVE_THERAPIST_DOCUMENT_FAILURE = 'REMOVE_THERAPIST_DOCUMENT_FAILURE';
