// account:
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ACTIVATION_REQUEST = 'ACTIVATION_REQUEST';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REFRESH_REQUEST = 'REFRESH_REQUEST';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAILURE = 'REFRESH_FAILURE';

export const LOGOUT = 'LOGOUT';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const GET_PERSONAL_THERAPIST_INFO_REQUEST = 'GET_PERSONAL_THERAPIST_INFO_REQUEST';
export const GET_PERSONAL_THERAPIST_INFO_SUCCESS = 'GET_PERSONAL_THERAPIST_INFO_SUCCESS';
export const GET_PERSONAL_THERAPIST_INFO_FAILURE = 'GET_PERSONAL_THERAPIST_INFO_FAILURE';

export const UPDATE_PERSONAL_THERAPIST_INFO_REQUEST = 'UPDATE_PERSONAL_THERAPIST_INFO_REQUEST';
export const UPDATE_PERSONAL_THERAPIST_INFO_SUCCESS = 'UPDATE_PERSONAL_THERAPIST_INFO_SUCCESS';
export const UPDATE_PERSONAL_THERAPIST_INFO_FAILURE = 'UPDATE_PERSONAL_THERAPIST_INFO_FAILURE';

export const REMOVE_THERAPIST_DOCUMENT_REQUEST = 'REMOVE_THERAPIST_DOCUMENT_REQUEST';
export const REMOVE_THERAPIST_DOCUMENT_SUCCESS = 'REMOVE_THERAPIST_DOCUMENT_SUCCESS';
export const REMOVE_THERAPIST_DOCUMENT_FAILURE = 'REMOVE_THERAPIST_DOCUMENT_FAILURE';

export const ADD_THERAPIST_DOCUMENT_REQUEST = 'ADD_THERAPIST_DOCUMENT_REQUEST';
export const ADD_THERAPIST_DOCUMENT_SUCCESS = 'ADD_THERAPIST_DOCUMENT_SUCCESS';
export const ADD_THERAPIST_DOCUMENT_FAILURE = 'ADD_THERAPIST_DOCUMENT_FAILURE';

export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST';
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS';
export const DEPOSIT_FAILURE = 'DEPOSIT_FAILURE';

export const REDIRECT_TO_PAYMENT_PAGE = 'REDIRECT_TO_PAYMENT_PAGE';

export const VERIFY_DEPOSIT_REQUEST = 'VERIFY_DEPOSIT_REQUEST';
export const VERIFY_DEPOSIT_SUCCESS = 'VERIFY_DEPOSIT_SUCCESS';
export const VERIFY_DEPOSIT_FAILURE = 'VERIFY_DEPOSIT_FAILURE';

export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAILURE = 'WITHDRAW_FAILURE';

export const GET_THERAPISTS_SUCCESS = 'GET_THERAPISTS_SUCCESS';
export const GET_THERAPISTS_REQUEST = 'GET_THERAPISTS_REQUEST';
export const GET_THERAPISTS_FAILURE = 'GET_THERAPISTS_FAILURE';
